name: RSpec

on: [pull_request]

jobs:
  integration_test_with_alpine:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ['2.7', '3.0']
    name: (Ruby${{ matrix.ruby_version }}-alpine) Integration Test
    runs-on: ubuntu-latest
    container: ruby:${{ matrix.ruby_version }}-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          gem install bundler -v 2.2.3
          apk add --no-cache build-base chromium git
          bundle install
      - name: RSpec
        run: bundle exec rspec --profile 10 --failure-exit-code 0 --format documentation spec/integration/
        env:
          PUPPETEER_NO_SANDBOX_RSPEC: true
        timeout-minutes: 20
      - name: RSpec (Retry)
        run: bundle exec rspec --profile 10 --only-failures --format documentation spec/integration/
        env:
          DEBUG: 1
          PUPPETEER_NO_SANDBOX_RSPEC: true
        timeout-minutes: 5
